-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 11:33:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaBD` DEFAULT CHARACTER SET utf8 ;
USE `sistemaBD` ;

-- -----------------------------------------------------
-- Table `sistemaBD`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `tipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`CURSO` (
  `idCURSO` INT NOT NULL AUTO_INCREMENT,
  `nombreCurso` VARCHAR(150) NOT NULL,
  `fechaInicio` VARCHAR(45) NOT NULL,
  `fechaFin` VARCHAR(45) NOT NULL,
  `objetivoCurso` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `duracionCurso` VARCHAR(45) NOT NULL,
  `destinatarios` VARCHAR(45) NOT NULL,
  `idINSTRUCTOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`DOCUMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`DOCUMENTO` (
  `idDOCUMENTO` INT NOT NULL AUTO_INCREMENT,
  `idCURSO` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `valido` INT NOT NULL,
  `rutaArchivo` VARCHAR(100) NULL,
  `idCURSO` INT NOT NULL,
  PRIMARY KEY (`idDOCUMENTO`, `idCURSO`),
  INDEX `fk_DOCUMENTO_CURSO_idx` (`idCURSO` ASC) VISIBLE,
  CONSTRAINT `fk_DOCUMENTO_CURSO`
    FOREIGN KEY (`idCURSO`)
    REFERENCES `sistemaBD`.`CURSO` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`CONSTANCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`CONSTANCIA` (
  `idCONSTANCIA` INT NOT NULL,
  `folio` VARCHAR(10) NOT NULL,
  `idCurso` INT NOT NULL,
  `idUSUARIO` INT NOT NULL,
  PRIMARY KEY (`idCONSTANCIA`),
  INDEX `fk_CONSTANCIA_USUARIO1_idx` (`idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_CONSTANCIA_USUARIO1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `sistemaBD`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`ASISTENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`ASISTENCIA` (
  `idASISTENCIA` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `asistencia` INT NOT NULL,
  PRIMARY KEY (`idASISTENCIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`ENCUESTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`ENCUESTA` (
  `idENCUESTA` INT NOT NULL,
  `pregunta` VARCHAR(150) NOT NULL,
  `puntuacion` INT NOT NULL,
  PRIMARY KEY (`idENCUESTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`USUARIO_INSCRITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`USUARIO_INSCRITO` (
  `idUSUARIO` INT NOT NULL,
  `idCURSO` INT NOT NULL,
  PRIMARY KEY (`idUSUARIO`, `idCURSO`),
  INDEX `fk_USUARIO_has_CURSO_CURSO1_idx` (`idCURSO` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_CURSO_USUARIO1_idx` (`idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_CURSO_USUARIO1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `sistemaBD`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_CURSO_CURSO1`
    FOREIGN KEY (`idCURSO`)
    REFERENCES `sistemaBD`.`CURSO` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaBD`.`USUARIO_has_ENCUESTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaBD`.`USUARIO_has_ENCUESTA` (
  `idUSUARIO` INT NOT NULL,
  `idENCUESTA` INT NOT NULL,
  PRIMARY KEY (`idUSUARIO`, `idENCUESTA`),
  INDEX `fk_USUARIO_has_ENCUESTA_ENCUESTA1_idx` (`idENCUESTA` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_ENCUESTA_USUARIO1_idx` (`idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_ENCUESTA_USUARIO1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `sistemaBD`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_ENCUESTA_ENCUESTA1`
    FOREIGN KEY (`idENCUESTA`)
    REFERENCES `sistemaBD`.`ENCUESTA` (`idENCUESTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
